import { useRouter } from 'next/router';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const router = useRouter();

  const handleClick = () => {
    router.push('./dashboard');
  };

  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>CoinManage</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <nav className={styles.navbar}>
        <h1 className={styles.navbarTitle}>CoinManage</h1>
        <div onClick={handleClick} className={styles.navbarButton}>
          <ConnectButton />
        </div>
      </nav>

      <main className={styles.main}>
        <p className={`${styles.title} ${styles.largeText}`}>
        Welcome to our all-in-one platform designed to simplify the management and payments between freelancers and service clients. We have created an intuitive and efficient ecosystem that offers an exceptional experience for both clients and independent professionals.
        </p>

      </main>

      <footer className={`${styles.footer} ${styles.stickyFooter}`}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>

    </div>
  );
};

export default Home;
